export const testimonialsdata = [
  {
    id: 1,
    name: "Ahmer khan",
    role: "Web Developer",
    image: "ahmer.jpeg",
    text: "Eman demonstrates solid frontend development skills with clean component structure and responsive design. Her use of React and Tailwind shows good practical understanding, and she’s steadily improving her debugging abilities.",
    rating: "3.0",
  },
  {
    id: 2,
    name: "Junaid Saeed",
    role: "Digital Marketer",
    image: "junaid.jpeg",
    text: "Her work aligns well with modern digital trends. The layouts are engaging and user-friendly, which helps in improving user retention and overall conversion potential",
    rating: "2.0",
  },
  {
    id: 3,
    name: "Hamza Rafiq",
    role: "Ui/Ux Designer",
    image: "hamza.jpeg",
    text: "Eman creates visually appealing and modern interfaces. Her sense of color, spacing, and layout is strong, though refining pixel-perfect detailing would elevate her work further",
    rating: "4.0",
  },
  {
    id: 4,
    name: "Amna Shahid",
    role: "Digital Markter",
    image: "amna.jpeg",
    text: "Her designs are clean and structured, making them effective for branding and marketing campaigns. She understands how to present content in a way that attracts users.",
    rating: "2.0",
  },
  {
    id: 5,
    name: "Hussnain Kabir",
    role: "Ui/Ux Designer",
    image: "nany.jpeg",
    text: "Her UI work is elegant and minimalistic. She focuses well on user experience and consistency, and with more attention to micro-details, her designs can reach a professional level.",
    rating: "3.0",
  },
]